
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      # working-directory'yi sadece Backend olarak değiştirin
      working-directory: Backend # DİKKAT: Sadece "Backend" olarak güncelledik
      run: docker build . --file Dockerfile -t my-image-name:${{ github.sha }}
