name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      # Çalışma dizinini "FavPlace/Backend" klasörüne ayarlıyoruz
      # Bu satır, üstündeki '- name:' ile aynı hizada değil, 2 boşluk daha içeride olmalı.
      working-directory: FavPlace/Backend
      # 'run' komutu da 'working-directory' ile aynı hizada olmalı.
      # Çalışma dizini ayarlandığı için, Dockerfile ve bağlam yolları kısaltıldı.
      run: docker build . --file Dockerfile -t my-image-name:${{ github.sha }}
